### ISSUE TITLE
Add more API documentation

### ISSUE THREAD

**Issue by mleonhard** [hse-project/mpool#1]
Hi HSE Team,
Thanks for releasing this code.

The [Wiki / API Reference page](https://github.com/hse-project/mpool/wiki/API-Reference) says "See the mpool API documentation in the [mpool.h](https://github.com/hse-project/mpool/blob/master/include/mpool/mpool.h) header file."  That file contains functions for operating on various data structures and objects.  How about adding some explanations of those data structures and how to use them?  This would make the code more useful.
- `mpool`
  - params
  - properties
  - device properties
- `mclass`
- `mlog`
  - This needs extra careful explanation of the structure of `mlog` objects.
  - What does it mean to skip bytes inside it?
  - Does `mpool_mlog_erase()` actually zero the bytes or just send a "trim" command to the SSD?
- `objid`, OID
- `mdc`
  - `mdc_capacity`
  - properties
  - compaction
- `mblock`
  - properties
- `mpool_mcache_map`
- Details of how to properly use asynchronous modes of certain functions. Explain how to detect completion and errors.
- Explain the proper way to handle errors from the API.
- State the runtimes of functions.  For example, say whether or not `mpool_mlog_len()` reads the whole object.

Best,
Michael

**Comment by smoyergh** [comment]
The mpool API is undergoing revision, as discussed in the Concepts section of the Wiki.  We expect to finalize the API documentation once complete.  The HSE API is stable, and documented in [hse.h](https://github.com/hse-project/hse/blob/master/include/hse/hse.h).
