### ISSUE TITLE
the folder scripts has a CMakeLists empty

### ISSUE THREAD

**Issue by Azaretdodo** [hse-project/mpool#11]
hello,

the scripts folder has a CMakeLists empty,

I have tried this following but it miss the tingting syntactic and the file isn't enough typed :

```
cmake_minimum_required( VERSION 3.6 )

cmake_policy( SET CMP0046 NEW )
cmake-policy( SET CMP0053 NEW )

project ( scripts C )
set( PROJECT_VERSION            "${BUILD_PKG_VERSION}")
set( PROJECT_HOMEPAGE_URL       "https://github.com/hse-project/mpool/tree/master/scripts" )
set( CMAKE_PROJECT_VERSION      "${PROJECT_VERSION}" )
set( CMAKE_PROJECT_HOMEPAGE_URL "${PROJECT_HOMEPAGE_URL}" )

message( STATUS "Configuring project ${PROJECT_NAME} ${PROJECT_VERSION} ${PROJECT_HOMEPAGE_URL} ${BUILD_PKG_TAG} commo>

set( CMAKE_C_STANDART 99 )
set( CMAKE_INSTALL_PREFIX /usr )

include(deb)
include(modules-load.d)
include(sysctl.d)
include(tmpfiles.d)
include(cmake)
include(dev)
include(rpm)
include(systemd)
include(udev)

set( SCRIPTS_DEB_INSTALL_PREFIX         ${PROJECT_BINARY_DIR}/deb)
set( SCRIPTS_MODULES-LOAD.D_PREFIX      ${PROJECT_BINARY_DIR}/modules-load.d)
set( SCRIPTS_SYSCTL.D_PREFIX            ${PROJECT_BINARY_DIR}/sysctl.d)
set( SCRIPTS_TMPFILES.D_PREFIX          ${PROJECT_BINARY_DIR}/tmpfiles.d)
set( SCRIPTS_CMAKE_DIR                  ${PROJECT_SOURCE_DIR}/cmake)
set( SCRIPTS_DEV_PREFIX                 ${PROJECT_BINARY_DIR}/dev)
set( SCRIPTS_RPM_PREFIX                 ${PROJECT_BINARY_DIR}/rpm)
set( SCRIPTS_SYSTEMD_PREFIX             ${PROJECT_BINARY_DIR}/systemd)
set( SCRIPTS_udev_PREFIX                ${PROJECT_BINARY_DIR}/udev)

set( CMAKE_RUNTIME_OUTPUT_DIRECTORY  ${MPOOL_STAGE_INSTALL_PREFIX}/bin)

add_compile_options(
    ${BUILD_CFLAGS} -g3 -std=gnu99 -Wall -Werror
    -Wlogical-op -Wno-missing-field-initializers -Wuninitialized -Wmaybe-uninitialized
    -Wextra -Wno-conversion -Wno-sign-conversion -Wno-sign-compare -Wno-unused-parameter
    )


file( WRITE ${CMAKE_BINARY_DIR}/CTestCustom.cmake.in )

configure_file( ${CMAKE_BINARY_DIR}CTestCustom.cmake.in
        ${RPM_BINARY_DIR}mpool-devel.spec.in 
        ${RPM_BINARY_DIR}mpool-test.spec.in 
        ${RPM_BINARY_DIR}mpool.spec.in
)
```

when I run the cmake .. in build directory I have following : 

```

[root@localhost scripts]# ls
CMkeLists.txt  build  deb  modules-load.d  sysctl.d  tmpfiles.d
bin            cmake  dev  rpm             systemd   udev
[root@localhost scripts]# cd build
[root@localhost build]# cmake ..
[root@localhhe source directory "/etc/openmpi-4.1.1/mpool/scripts" does not appear to contain CMakeList,s.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```
in the mpool build directorie the cmake .. answer following : 

```
 [root@localhost build]# cmake ..
-- Configuring project mpool   common...
CMake Error at CMakeLists.txt:25 (include):
  include could not find load file:

    /etc/openmpi-4.1.1/mpool/scripts/


-- Enabling valgrind support
-- Configuring mpool in /etc/openmpi-4.1.1/mpool/src/mpool
-- Configuring mpool in /etc/openmpi-4.1.1/mpool/src/mptest
-- Configuring ui /etc/openmpi-4.1.1/mpool/src/cli
-- Configuring mcache_api in /etc/openmpi-4.1.1/mpool/test/test_apps/mcache_api
-- Configuring mpiotest in /etc/openmpi-4.1.1/mpool/test/test_apps/mpiotest
-- Configuring ui /etc/openmpi-4.1.1/mpool/test/test_apps/mpft
-- Configuring mpool samples in /etc/openmpi-4.1.1/mpool/samples
CMake Error at CMakeLists.txt:231 (include):
  include could not find load file:

    /etc/openmpi-4.1.1/mpool/etc/openmpi-4.1.1/mpool/scripts/CMakeLists.txt


CMake Error: File /etc/openmpi-4.1.1/mpool/etc/openmpi-4.1.1/mpool/scripts/cmake/CTestCustom.cmake.in does not exist.
CMake Error at CMakeLists.txt:237 (configure_file):
  configure_file Problem configuring file


-- Compiler flags:
 --   INCLUDE_DIRECTORIES     /etc/openmpi-4.1.1/mpool/build/ext_install/include;/etc/openmpi-4.1.1/mpool/build/stage/include
--   COMPILE_DEFINITIONS     
--   COMPILE_OPTIONS         -g3;-std=gnu99;-Wall;-Werror;-Wlogical-op;-Wno-missing-field-initializers;-Wuninitialized;-Wmaybe-uniniti1. alized;-Wextra;-Wno-conversion;-Wno-sign-conversion;-Wno-sign-compare;-Wno-unused-parameter;-Wimplic6it-fallthrough=0;-fPIC
--   LINK_DIRECTORIES        
--   LINK_LIBRARIES          
--   LINK_OPTIONS            
-- Configuring incomplete, errors occurred!
See also "/etc/openmpi-4.1.1/mpool/build/CMakeFiles/CMakeOutput.log".
```
 
Thank you in advance to help myself fully run scripts of cmake compiling,

Regards.

Azaretdodo.

**Comment by smoyerx** [comment]
With the [pre-release](https://github.com/hse-project/hse/discussions/45) of HSE 2.0 we are no longer maintaining mpool.  For building the most recent (and last) version of mpool, please be sure you've met all [system requirements](https://github.com/hse-project/mpool/wiki/System-Requirements) and have followed all the steps in the instructions on [building from source](https://github.com/hse-project/mpool/wiki/Install-from-Source).

We encourage you to upgrade to HSE 2.0 which does not rely on mpool.

**Comment by Azaretdodo** [comment]
I am on mpool because the deliverer of update for hardware openmpi ask mpool on the make check line of command

Does HSE is Independent ?

Thank you in advance for your answer,

Regards.


Azaretdodo.

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Azaretdodo** [comment]
Does HSE is Independent and delive update of hardware for SSD... SSHDD...and MVME ?

Thank you in advance for your answer,

Regards.


Azaretdodo.

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by smoyerx** [comment]
There is no relationship between our work and openmpi.  A quick Google search indicates that openmpi includes a framework called "memory pool management", also called mpool.  See [here](https://www.open-mpi.org/faq/?category=tuning#frameworks-v1.2-and-prior).

**Comment by Azaretdodo** [comment]
Openmpi is a deliverer of update of hardware,

And a memory can be dead and called ROM,

Mpool support delive of ROM hardware as SSD mostly for leave to support SSHDD and nvme,

Does HSE 2.0 delive update of hardwy for the three solid state hardware ?

Thank you in advance for your answer,

Regards.


Azaretdodo.
________________________________

**Comment by Azaretdodo** [comment]
Oh Bad you have the thrue:


Mpool: Object Storage Media Pool

Notice: HSE<https://github.com/hse-project/hse> versions 2.0 and later do not make use of mpool. As a result, mpool is no longer actively maintained.

Mpool is a Linux® loadable kernel module that implements an object storage device interface for SSDs and other solid-state storage. It provides a high-performance alternative to file systems or raw block devices for applications that can benefit from its simple object storage model and unique features.

Key Features

  *   Object storage model comprising immutable blocks (blobs) and appendable logs
  *   Objects can optionally be placed on multiple classes of solid-state storage
  *   Facilities to memory-map arbitrary collections of block objects into a linear address space
  *   Proactive management of block object data in the Linux page cache based on object-level usage metrics
  *   Simultaneously access block object data directly and memory-mapped with no performance penalty
  *   Management model and CLI similar to that of Linux LVM
  *   C API library that can be embedded in any application

Sorry,

Regards.


Azaretdodo.
Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by smoyerx** [comment]
No problem.  I hope you find what you're looking for elsewhere.

**Comment by Azaretdodo** [comment]
HSE is adviced in a PaaS ?

Thank you in advance for your answer,

Regards.


Azaretdodo.

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by smoyerx** [comment]
HSE is appropriate for any application requiring a key-value storage engine.  You can find examples of such applications in a variety of domains: Databases, Software-defined Storage, Stream Processing, Machine Learning, HPC, etc.

**Comment by Azaretdodo** [comment]
I am hosting the last Facebook for computers and tablet all Big screen,

You adviced HSE for ?

Thank you in advance for your answer,

Regards.


Azaretdodo.

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by smoyerx** [comment]
HSE is a library.  You code to the HSE API and link the HSE library with your application.  Only you can decide if your application can benefit from the functionality that the HSE library implements.

**Comment by Azaretdodo** [comment]
I am not really a devlopper i have more edited cmake scripts sorry i haven't an utility with HSE,

Have a good end of weekend from the France it is twenty one past quarter here,

Regards.


Azaretdodo.

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
