### ISSUE TITLE
upstream hope/timeline?

### ISSUE THREAD

**Issue by vicaya** [hse-project/mpool#3]
Any hope/timeline to get the kernel module upstreamed? Cursory google didn't turn up relevant threads.

**Comment by smoyergh** [comment]
We haven't yet submitted the patch set for upstream, though we're actively working with several upstream maintainers on enhancements prior to submission.  We can't commit to a specific timeline for when we'll submit the patch set, but it won't be too much longer.  And of course how long it will take the patch set to be accepted is a community decision.

**Comment by WSLUser** [comment]
Status update?

**Comment by smoyergh** [comment]
We submitted the patch set to upstream on 9/28/2020.  The net of the discussion was several key maintainers felt that object store functionality should be restricted to user space.

For this and other reasons we are taking different architectural approach with HSE that will obviate the need for a kernel component.  This will be reflected in an upcoming release of HSE, though I cannot provide specifics on timing.
