### ISSUE TITLE
mpool on ARM

### ISSUE THREAD

**Issue by victorstewart** [hse-project/mpool#5]
i saw the requirements said x86. so no ARM support correct? if so, where does the limitation exist?

**Comment by smoyergh** [comment]
We have only built and tested on x86.  Feel free to build on ARM, give it a try, and let us know how it goes.

**Comment by victorstewart** [comment]
i'll update here when I get a chance. could be a while!

**Comment by smoyergh** [comment]
A future release of HSE will obviate the need for a kernel component, which should greatly simplify ARM support for HSE.

**Comment by victorstewart** [comment]
@smoyergh at no performance cost?

**Comment by smoyergh** [comment]
We are not expecting a performance impact, based on the testing and analysis we conducted as part of the redesign effort.

**Comment by smoyerx** [comment]
HSE 2.0 should make it much easier to port to ARM.
