### ISSUE TITLE
Occasional Lingering Open Mpool When SIGKILL-ing Process

### ISSUE THREAD

**Issue by victorstewart** [hse-project/mpool#7]
not every time... but every few dozen times that i `pkill -KILL processname` my mpool gets stuck. 

so when i try to destroy it I get resource busy (even though the process is 100% dead)...

```
root@clr-fc2a36cf35a645a0a1e17af84fb1eab8~ # mpool destroy hotmpool
mpool: Unable to destroy mpool hotmpool (mpool/mpctl.c:142: Device or resource busy)
```
have you ever seen this before? is there any way I can force destroy it in these circumstances besides rebooting the machine?

also makes me a bit worried that if the application was killed by the OS in production that the mpool would be unrecoverable without a reboot... or at the very least terminal-ing into the machine.

i can collect any data you need so that next time it happens i can share them.

**Comment by victorstewart** [comment]
just had a situation where my application segfaulted, but in my signal handler I closed the KVSs and the KVDB and then called `hse_kvdb_fini()`, but still the mpool was stuck.

**Comment by smoyergh** [comment]
What is your distro and kernel?  We only test mpool with the limited set of RHEL 7/8 and Ubuntu 18.04 distros listed in the Wiki.

**Comment by victorstewart** [comment]
Clear Linux 5.10.15-1024.native

I can do any necessary detective work if you point me in the right directions

**Comment by nabeelmmd** [comment]
@victorstewart, when the "mpool destroy" fails, are there any mpool related messages in the kernel log? Something like "hotmpool: busy, cannot deactivate".

In mpool-kmod repository, mpctl.c:
```
static int mp_deactivate_impl(struct mpc_unit *ctl, struct mpioc_mpool *mp, bool locked)
{
    ...
    if (unit->un_open_cnt > 0 || kref_read(&unit->un_ref) != 2) {
        rc = -EBUSY;
        mp_pr_err("%s: busy, cannot deactivate", rc, unit->un_name);    <<<<<<<<<<
    }
}
```
If the above message is seen in the kernel log, then that implies either or both of the following.

(1) The release handler (mpctl_release()) wasn't called for the mpool device, leaving the device file open count to be >0. Please check "fuser /dev/mpool/hotmpool" and ensure that there's no process holding on to the mpool's device file (/dev/mpool/hotmpool).

(2) A bug that causes the mpool unit's refcnt to be not equal to the expected value of 2.

If this error path is hit in your case, extending the above log message to print 'un_open_cnt' and 'un_ref' might be useful.

**Comment by victorstewart** [comment]
Just happened again. right this was in the kernel log...

`[168419.127535] mp_deactivate_impl: hotmpool: busy, cannot deactivate: errno -16`

 i tried `fuser /dev/mpool/hotmpool` and it produced no output. (as to be expected the single process was most certainly killed).

this output might be useful

```
root@clr-59036175a93b4862844d506208366354~ # lsmod | grep mpool
mpool                 188416  3
```

should I add those prints of 'un_open_cnt' and 'un_ref' and then get back to you with the values?

**Comment by nabeelmmd** [comment]
Thanks! Yes, printing the values of 'un_open_cnt' and 'un_ref' in mp_deactivate_impl() will help us here.
```
mp_pr_err("%s: busy, cannot deactivate, open count %d unit ref %d",
        rc, unit->un_name, unit->un_open_cnt, kref_read(&unit->un_ref));
```
Also, if it's not too much noise for your app, could you please add the following printk in mpc_release()? Just want to make sure the release handler is getting called when this problem occurs.
```
static int mpc_release(struct inode *ip, struct file *fp)
{
    ....
    down(&unit->un_open_lock);
    printk(KERN_ERR "%s: %s: open count: %d unit ref: %d",
        __func__, unit->un_name, unit->un_open_cnt, kref_read(&unit->un_ref));
    lastclose = (--unit->un_open_cnt == 0);
    if (!lastclose)
        goto errout;
    ....
}
```
Which HSE version are you running on? I tried multiple times to recreate this issue in my setup (on Ubuntu 18), but haven't succeeded so far.

**Comment by victorstewart** [comment]
just added both, will report back when it happens again. I'm running 1.9.0 HSE and Mpool... I cloned the git repository and checkedout 1.9.0.

**Comment by victorstewart** [comment]
just got this

```
[20978.561700] mp_deactivate_impl: hotmpool: busy, cannot deactivate, open count 0 unit ref 3: errno -16
[20978.567518] mpioc_mp_cmd: hotmpool: deactivate failed: errno -16
```

**Comment by nabeelmmd** [comment]
Thanks for the debug logs! I briefly looked at this today and completely puzzled with what's going on here. 

The release hander (mpc_release()) did get called as an effect of the application closing kvdb. The mpool's ref was 2 on entering this handler, which is expected. Just before returning from this handler, the reference would have got decremented by 1.

On entering mp_deactivate_impl(), the reference got incremented by 1. Assuming that nothing else happened on this mpool between application shutdown and mpool destroy, the expected reference in the EBUSY check is 2. Interestingly, the log in mp_deactivate_impl() shows the reference as 3.

The only way I could explain this currently is that some other mpool operation racing with mpool destroy is incrementing the ref by 1 and not letting the destroy to complete, like a sideband thread listing kvdbs in a loop or something similar.. Or may be there's something else that I'm not seeing yet...

```
[20978.558931] mpc_release: hotmpool: open count: 1 unit ref: 2
[20978.561700] mp_deactivate_impl: hotmpool: busy, cannot deactivate, open count 0 unit ref 3: errno -16
[20978.567518] mpioc_mp_cmd: hotmpool: deactivate failed: errno -16
```
I'll keep looking. Any pointers from your end on the repro. steps will be greatly appreciated.

Unfortunately, we don't have a force mpool destroy to recover without a reboot. However, the good news is that a future HSE release will hopefully eliminate the kernel component which voids this issue and most importantly lets us recover without reboots.

**Comment by victorstewart** [comment]
it started happening less frequently and i still can't isolate a reproducible sequence + test program. and i guess ultimately this will be brushed away with the module-less version... but i'll leave the issue open for now in hopes i do.
